-- ELECTRICAL & ELECTRONICS QUIZ SYSTEM
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  admission_number text unique not null,
  role text not null default 'student'
    check (role in ('student','teacher','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('Beginner','Intermediate','Advanced')),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null check (correct_option in ('A','B','C','D')),
  explanation text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  level text not null check (level in ('Beginner','Intermediate','Advanced')),
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0),
  percentage numeric(5,2) not null check (percentage >= 0 and percentage <= 100),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, admission_number)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Student'),
    coalesce(new.raw_user_meta_data->>'admission_number', 'PENDING-' || left(new.id::text, 8))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_attempts enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.questions from anon, authenticated;
revoke all on public.quiz_attempts from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.questions to authenticated;
grant select, insert on public.quiz_attempts to authenticated;

-- Helper used by policies. It avoids asking the browser to decide whether someone is an admin.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('teacher','admin')
  );
$$;

drop policy if exists "users view own profile or staff view profiles" on public.profiles;
create policy "users view own profile or staff view profiles"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_staff());

drop policy if exists "authenticated users read active questions" on public.questions;
create policy "authenticated users read active questions"
on public.questions for select
to authenticated
using (is_active = true or public.is_staff());

drop policy if exists "students insert own attempts" on public.quiz_attempts;
create policy "students insert own attempts"
on public.quiz_attempts for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "users read own attempts or staff read all" on public.quiz_attempts;
create policy "users read own attempts or staff read all"
on public.quiz_attempts for select
to authenticated
using (user_id = auth.uid() or public.is_staff());

-- Public leaderboard view: only non-sensitive ranking fields are exposed.
create or replace view public.leaderboard
with (security_invoker = true)
as
select
  p.full_name,
  a.level,
  a.percentage,
  a.created_at
from public.quiz_attempts a
join public.profiles p on p.id = a.user_id
order by a.percentage desc, a.created_at asc;

-- Starter questions
insert into public.questions
(level, question, option_a, option_b, option_c, option_d, correct_option, explanation)
values
('Beginner','What is the SI unit of electrical resistance?','Volt','Ampere','Ohm','Watt','C','Resistance is measured in ohms (Ω).'),
('Beginner','Which instrument measures electric current?','Voltmeter','Ammeter','Ohmmeter','Wattmeter','B','An ammeter is connected to measure current.'),
('Beginner','Which component stores energy in an electric field?','Resistor','Inductor','Capacitor','Diode','C','A capacitor stores energy in its electric field.'),
('Beginner','Which law is represented by V = IR?','Faraday’s law','Ohm’s law','Lenz’s law','Coulomb’s law','B','Ohm’s law relates voltage, current and resistance.'),
('Beginner','What is the common AC supply frequency in Kenya?','25 Hz','40 Hz','50 Hz','60 Hz','C','Kenya uses a 50 Hz AC supply frequency.'),

('Intermediate','A 12 V supply is connected to a 6 Ω resistor. What current flows?','0.5 A','2 A','6 A','72 A','B','Using I = V/R gives 12/6 = 2 A.'),
('Intermediate','Which device converts AC to DC?','Inverter','Rectifier','Oscillator','Transformer','B','A rectifier converts alternating current to direct current.'),
('Intermediate','Which semiconductor device normally conducts mainly in one direction?','Diode','Capacitor','Relay','Transformer','A','A diode provides one-way current conduction under normal operation.'),
('Intermediate','What is the main purpose of a transformer?','Store charge','Change AC voltage level','Convert DC to AC','Measure resistance','B','Transformers transfer AC energy and change voltage/current levels.'),
('Intermediate','In a series circuit, which quantity is the same through all components?','Voltage','Current','Power','Resistance','B','The same current flows through every series element.'),

('Advanced','Which principle states that an induced current opposes the change that produced it?','Ohm’s law','Lenz’s law','Kirchhoff’s current law','Coulomb’s law','B','Lenz’s law gives the direction of induced current.'),
('Advanced','Which device is commonly used as an electronic switch and amplifier?','Transistor','Fuse','Capacitor','Transformer','A','Transistors can operate as switches and amplifying devices.'),
('Advanced','What is the power factor of a purely resistive AC load?','0','0.5','1','2','C','Voltage and current are in phase for a purely resistive load, giving PF = 1.'),
('Advanced','Which logic gate gives HIGH output only when all inputs are HIGH?','OR','AND','XOR','NOT','B','The AND gate output is HIGH only when all inputs are HIGH.'),
('Advanced','Which instrument measures real electrical power in a circuit?','Ammeter','Voltmeter','Wattmeter','Ohmmeter','C','A wattmeter measures electrical power in watts.');

-- After you register your teacher/admin account, run one of these:
-- update public.profiles set role = 'admin' where admission_number = 'ADMIN001';
-- OR
-- update public.profiles set role = 'teacher' where admission_number = 'TEACHER001';
